### ISSUE TITLE
Benchmark 

### ISSUE THREAD

**Issue by cosme12** [MiguelMJ/Milua#6]
Hey, awesome project! I have been looking for some really simple web framework to keep learning Lua and found this. And it also looks similar to what I'm used to work with (Flask).

Now my question is, have you ever made any kind of benchmark to compare it with other frameworks? It's just to have an idea of what to expect. Thanks!

**Comment by MiguelMJ** [comment]
Hello, cosme12!
I'm glad you liked Milua! Flask was actually the main inspiration to do it.
I haven't benchmarked the framework, actually.  Is something I have not much experience with, and afaik is not a trivial thing to do.
I'll let this issue open in case someone feels like doing it. I would gladly include them as a contributor!
