### ISSUE TITLE
module 'milua_config' not found:

### ISSUE THREAD

**Issue by ilyafreer** [MiguelMJ/Milua#8]
luarocks install milua

use config like example and get error

/app # lua server_start.lua 
lua: server_start.lua:2: module 'milua_config' not found:
        no field package.preload['milua_config']
        no file '/usr/local/share/lua/5.4/milua_config.lua'
        no file '/usr/local/share/lua/5.4/milua_config/init.lua'
        no file '/usr/local/lib/lua/5.4/milua_config.lua'
        no file '/usr/local/lib/lua/5.4/milua_config/init.lua'
        no file './milua_config.lua'
        no file './milua_config/init.lua'
        no file '/usr/local/lib/lua/5.4/milua_config.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './milua_config.so'
stack traceback:
        [C]: in function 'require'
        server_start.lua:2: in main chunk
        [C]: in ?

**Comment by MiguelMJ** [comment]
@wmb1207 implemented the config submodule, maybe he can have a look at it. I will check it, however, when I have some time.
Thanks a lot for reporting! If there's any news about this issue comment again, please

**Comment by wmb1207** [comment]
Can you share your `server_start.lua`?

I just tested a clean build and it's working for me.

Here is the example I just tested

```lua
local app = require "milua"
local Config = require("milua_config")

Config:extend({
    DB_NAME="name",
    DB_PASS="pass",
    DB_HOST="host",
    HOST="localhost",
    STDOUT="localhost",
    WOLOLOLO=""
})

app.start(Config)
-- Basic example
app.add_handler(
    "GET",
    "/",
    function()
        return "<h1>Welcome to the handsome server!</h1>"
    end
)

-- Example capturing a path variable
app.add_handler(
    "GET",
    "/user/...", 
    function (captures, query, headers)

        local username = captures[1]
        local times = query.times or 1
        return "The user " .. username .. " is" .. (" very"):rep(times) .. " handsome"
    
    end
)

```

**Comment by rdleal** [comment]
I'm getting the same error as @ilyafreer.

I installed the package through `luarocks` command, as suggested in the [installation](https://github.com/MiguelMJ/Milua#installation) section of the README.md. 

After investigating for a while, I noticed that the [manifest uploaded](https://luarocks.org/manifests/MiguelMJ/milua-0.1-1.rockspec) to the luarocks server only list the file `milua.lua` in the `modules` session:

```
package = "milua"
version = "0.1-1"
source = {
   url = "git+https://github.com/MiguelMJ/Milua",
   tag = "v0.1"
}
description = {
   summary = "Micro framework for web applications",
   homepage = "https://github.com/MiguelMJ/Milua",
   license = "MIT"
}
dependencies = {
   "lua ~> 5.4",
   "http ~> 0.4",
   "net-url ~> 1.1-1",
   "luaposix ~> 35.1-1"
}
build = {
   type = "builtin",
   modules = {
      milua = "src/milua.lua"
   }
```

So I thing the issue might be on the version uploaded to the luarocks server. Maybe you guys need to create a new tag and upload a new `.rockspec` file to luarocks in order for everyone to be able to use the `milua_config` module properly.

**Comment by MiguelMJ** [comment]
@rdleal you are right! 🥲 
I have just updated the luarocks version, so the package should include the milua config, log and utils modules when the changes propagate. I'm closing the issue now, but please kindly report any news about this. Thank you!

**Comment by MiguelMJ** [comment]
Update: The version 2.0-1 still didn't work
The **version 2.0-2** does! I had to change the build system because even with the update rockspec the modules were not available for import.

Solution used: https://stackoverflow.com/a/34968954/8757033
