### ISSUE TITLE
haven't access outside docker

### ISSUE THREAD

**Issue by ilyafreer** [MiguelMJ/Milua#9]
ports:
      - '8080:8080'

requests outside container don't answer
inside all is good

**Comment by MiguelMJ** [comment]
Do other services respond from outside? It would be good to know if it is a Milua thing or another problem with the container configuration (I don't have much experience with Docker)

**Comment by wmb1207** [comment]
To have Access from outside a docker container make sure to set the config your server to listen on `0.0.0.0` and the right port
```lua
Config:extend({
    HOST="0.0.0.0",
    PORT="8080",
})

```
